
#load packages 
library(BiocManager)
library(tximport)
library(DESeq2)
library(plotly)
library(pheatmap)
library(RColorBrewer)
library(tidyverse)

#file import and organisation

human.gct <- read.delim(file="gene_reads_2017-06-05_v8_brain_cortex.gct.gz", skip=2)

healthy_human <- read.csv("healthy_human.csv")
read.csv("tx2gene.csv.gz") %>% View()

prim_sample_info <- read.csv("primary_healthy_sample_info.csv")

gbm_sample_files <- paste0(pull(gbm_sample_info,'sample_id'), '/quant.sf')

names(gbm_sample_files) <- pull(gbm_sample_info, 'id')

gbm_count_data <- tximport(files = gbm_sample_files,
         type = "salmon",
         tx2gene = human_tx2gene,
         ignoreTxVersion = T,
         dropInfReps = TRUE)


#how to look at count data (the important part)
tail(count_data[['counts']])
#or
View(gbm_count_data$counts) 

#differential expression analysis


#need to make the variable of interest a factor 
cond <- list(prim_sample_info$tumour)
cond <- factor(cond, levels = "healthy", "gbm")
        

prim_h_dds <- cond


#txi -> data generated by tximport
#colData -> metadata/column data to go along with salmon txi data (sample_info)
#design is "equation description of experiment"
# ~ represents 'given' ie y ~ x, where y is implied (x=factor)

prim_h_dds <- DESeqDataSetFromMatrix(countData = combine_prim_health_counts,
                                     colData = prim_sample_info,
                                     design = ~tumour)



prim_h_dds <- estimateSizeFactors(prim_h_dds)
rec_h_dds <- estimateSizeFactors(rec_h_dds)

counts(prim_h_dds, normalized = T)
counts(gbm_dds)[1:6,1:14]

#plot raw count data -> very skewed to small values
boxplot(counts(prim_h_dds, normalized = T))
boxplot(counts(gbm_dds))

#transform data using vst
prim_h_vst <- varianceStabilizingTransformation(prim_h_dds)
rec_h_vst <- varianceStabilizingTransformation(rec_h_dds)


boxplot(assay(rec_h_vst))


h_prim_pca <- DESeq2::plotPCA(prim_h_vst, intgroup = "tumour") +
  theme_bw()

#Hierachical clustering of data (unsupervised)
#needs distance matrix (rather than observtional which is counts)

gbm_dist_dds <- dist(t(assay(prim_h_vst)))

gbm_hclust_dds <- hclust(gbm_dist_dds)
plot(gbm_hclust_dds)

#estimating dispersion of data

prim_h_dds <- estimateDispersions(prim_h_dds)
rec_h_dds <- estimateDispersions(rec_h_dds)
plotDispEsts(gbm_dds)

#apply statistics
#alphabetically compared by default -> GL261 compared with RAS
#+ log fold -> increase in RAS
#- log fold -> decrease in RAS/increase in GL261

prim_h_dds <- nbinomWaldTest(prim_h_dds)
results_prim_h_dds <- results(prim_h_dds)
summary(results_prim_h_dds)

rec_h_dds <- nbinomWaldTest(rec_h_dds)
results_rec_h_dds <- results(rec_h_dds)
summary(results_rec_h_dds)

View(as.data.frame(results_table_dds))

#convert results to data.frame

results_prim_dds_df <- as.data.frame(results_prim_h_dds)
results_rec_dds_df <- as.data.frame(results_rec_h_dds)

#remove genes from data.frame which have NA vaules

sum(complete.cases(results_prim_dds_df))
sum(complete.cases(results_rec_dds_df))

filtered_results_prim_dds_df <- results_prim_dds_df[complete.cases(results_prim_dds_df),]
filtered_results_rec_dds_df <- results_rec_dds_df[complete.cases(results_rec_dds_df),]

#filter results based on stat significance

# padj < 0.05 
# log2FoldChange > 1 or < -1

filtered_results_prim_dds_df$padj < 0.05
abs(filtered_results_prim_dds_df$log2FoldChange) > 1

prim_sig_0.05_df <- filtered_results_prim_dds_df[filtered_results_prim_dds_df$padj < 0.05,]
dim(prim_sig_0.05_df)

prim_sig_0.05_df <- prim_sig_0.05_df[abs(prim_sig_0.05_df$log2FoldChange) > 1,]
dim(prim_sig_0.05_df)

filtered_results_rec_dds_df$padj < 0.05
abs(filtered_results_rec_dds_df$log2FoldChange) > 1

rec_sig_0.05_df <- filtered_results_rec_dds_df[filtered_results_rec_dds_df$padj < 0.05,]
dim(rec_sig_0.05_df)

rec_sig_0.05_df <- rec_sig_0.05_df[abs(rec_sig_0.05_df$log2FoldChange) > 1,]
dim(rec_sig_0.05_df)

# padj < 0.01
# log2FoldChange > 1 or < -1

filtered_results_prim_dds_df$padj < 0.01
abs(filtered_results_prim_dds_df$log2FoldChange) > 1

prim_sig_0.01_df <- filtered_results_prim_dds_df[filtered_results_prim_dds_df$padj < 0.01,]
dim(prim_sig_0.01_df)

prim_sig_0.01_df <- prim_sig_0.01_df[abs(prim_sig_0.01_df$log2FoldChange) > 1,]
dim(prim_sig_0.01_df)

filtered_results_rec_dds_df$padj < 0.01
abs(filtered_results_rec_dds_df$log2FoldChange) > 1

rec_sig_0.01_df <- filtered_results_rec_dds_df[filtered_results_rec_dds_df$padj < 0.01,]
dim(rec_sig_0.01_df)

rec_sig_0.01_df <- rec_sig_0.01_df[abs(rec_sig_0.01_df$log2FoldChange) > 1,]
dim(rec_sig_0.01_df)

#MA plots
#

plotMA(results_prim_h_dds, 
       alpha = 0.05, 
       ylim = c(-10,10))

#volcano plots
# plots the log2FC against the padj value (-log10 of padj)

filtered_results_prim_dds_df$sig_test <- filtered_results_prim_dds_df$padj < 0.05 & abs(filtered_results_prim_dds_df$log2FoldChange) > 1

filtered_results_rec_dds_df$sig_test <- filtered_results_rec_dds_df$padj < 0.05 & abs(filtered_results_rec_dds_df$log2FoldChange) > 1

filtered_results_rvh_dds_df <- rownames_to_column(filtered_results_rvh_dds_df, var = 'Gene_name')

rec_h_v_plot <- ggplot(filtered_results_rec_dds_df, aes(x=log2FoldChange, y=-log10(padj), name=SYMBOL)) +
      geom_point(aes(colour = sig_test), size = 1, alpha = 0.5) +
      scale_colour_manual(values = c('grey', 'red')) +
      labs(title = "Differentially expressed genes between Primary GBM and healthy human cortex") +
      xlab("log2 Fold Change") + ylab("-log10 Padj")  +
      theme_bw() +
      theme(legend.position = "none", plot.title = element_text(hjust = 0.5))

ggplotly(rvh_V_plot)

#heatmaps

#need to get row_names -> columns for DEGs
#base heatmap package has less customisation 


prim_DEGs_5 <- prim_sig_0.05_df$SYMBOL
rec_DEGs_5 <- rec_sig_0.05_df$SYMBOL

prim_DEGs_1 <- prim_sig_0.01_df$SYMBOL
rec_DEGs_1 <- rec_sig_0.01_df$SYMBOL


prim_hm_data_5 <- prim_h_vst[prim_DEGs_5,]
prim_hm_data_5 <- as.matrix(prim_hm_data_5)
class(prim_hm_data_5) <- "numeric" 

prim_hm_data_1 <- prim_h_vst[prim_DEGs_1,]
prim_hm_data_1 <- as.matrix(prim_hm_data_1)
class(prim_hm_data_1) <- "numeric" 

rec_hm_data_5 <- rec_h_vst[rec_DEGs_5,]
rec_hm_data_5 <- as.matrix(rec_hm_data_5)
class(rec_hm_data_5) <- "numeric" 

rec_hm_data_1 <- rec_h_vst[rec_DEGs_1,]
rec_hm_data_1 <- as.matrix(rec_hm_data_1)
class(rec_hm_data_1) <- "numeric" 

heatmap(prim_hm_data_1)      

#pheatmaps has more input factors
#default is not to normalise across gene

PuRd_colour <- colorRampPalette(brewer.pal(9, "PuRd"))(100)

pheatmap(prim_hm_data_1, fontsize_row = 4,
         scale = 'row', color = PuRd_colour,
         show_rownames = F,
         main = 'Differentially expressed genes between primary GBM tumours and healthy cortex')
